Spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:funcionario
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format: true
  h2:
    console.enabled: true
  
  mvc:
    hiddenmethod:
      filter:
        enabled: true
